name: deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:
  

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        
        - name: Build webpage
          run: npm install && npm run build

        - name: Load SSH key
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            name: id_rsa
            known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
        
        - name: Deploy to Contabo
          run: scp -i /home/runner/.ssh/id_rsa -r ./dist ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PATH }}
